name: Maven Tests with Allure Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}  # manual run

permissions:
  contents: write  # required by actions-gh-pages to push to gh-pages

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the repository (main branch)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      # 3) Cache Maven dependencies for faster builds
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4) Install Chrome (used by Selenium in headless mode)
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      # 5) Optional: show Chrome version for diagnostics
      - name: Check Chrome version
        run: chrome --version

      # 6) Run tests (continue-on-error ensures report is still generated)
      - name: Run tests
        run: mvn -B clean test
        continue-on-error: true

      # 7) Debug: list target and allure-results to confirm outputs exist
      - name: Debug list target
        if: always()
        run: |
          echo "--- target content ---"
          ls -la target || true
          echo "--- allure-results content ---"
          ls -la target/allure-results || true

      # 8) Load existing Allure history from gh-pages (for trends)
      - name: Load Allure history
        if: always()
        uses: actions/checkout@v4
        with:
          ref: gh-pages            # checkout the gh-pages branch
          path: gh-pages           # into a separate folder
        continue-on-error: true    # first run may not have gh-pages yet

      # 9) Generate Allure report (simple-elf action outputs to allure-history/)
      - name: Generate Allure report
        if: always()
        uses: simple-elf/allure-report-action@v1.13
        with:
          gh_pages: gh-pages        # previously checked out history (input)
          allure_history: allure-history  # output folder with final static site
          allure_results: target/allure-results

      # 10) Deploy the report to gh-pages (skip on pull_request to avoid publishing)
      - name: Deploy report to gh-pages
        if: always() && github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
