name: Maven Tests with Allure Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}  # manual run

permissions:
  contents: write  # required by actions-gh-pages to push to gh-pages

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the repository (main branch)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Set up JDK 21 (match project target)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      # 3) Cache Maven dependencies for faster builds
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4) Install Chrome (used by Selenium in headless mode)
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      # 5) Optional: show Chrome version for diagnostics
      - name: Check Chrome version
        run: chrome --version

      # 6) Run tests (continue even if tests fail so report still publishes)
      - name: Run tests
        run: mvn -B clean test
        continue-on-error: true

      # 7) Debug: list target and allure-results to confirm outputs exist
      - name: Debug list target
        if: always()
        run: |
          echo "--- target content ---"
          ls -la target || true
          echo "--- allure-results content ---"
          ls -la target/allure-results || true

      # 8) Load existing Allure history from gh-pages (for trends)
      - name: Load Allure history
        if: always()
        uses: actions/checkout@v4
        with:
          ref: gh-pages            # checkout the gh-pages branch
          path: gh-pages           # into a separate folder
        continue-on-error: true    # first run may not have gh-pages yet

      # 9) Generate Allure report (outputs to allure-history/)
      - name: Generate Allure report
        if: always()
        uses: simple-elf/allure-report-action@v1.13
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: target/allure-results

      # 9.5) Create root index.html that redirects to the latest run
      #      (Place this STEP **after** generation and **before** deploy)
      - name: Point root index.html to latest report
        if: always()
        run: |
          cd allure-history
          # Find the latest numeric folder generated by Allure history
          latest=$(ls -1d [0-9]* 2>/dev/null | sort -n | tail -1)
          # Fallback to current directory if no numeric folders exist yet
          if [ -z "$latest" ]; then latest="."; fi
          cat > index.html <<'EOF'
          <!-- Auto-redirect to the latest Allure report -->
          <meta http-equiv="refresh" content="0; url=./LATEST_PLACEHOLDER/index.html" />
          <script>location.href="./LATEST_PLACEHOLDER/index.html";</script>
          EOF
          # Re
