name: Maven Tests with Allure Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}  # manual run

permissions:
  contents: write  # required by actions-gh-pages to push to gh-pages

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the repository (main branch)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      # 3) Cache Maven dependencies for faster builds
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4) Install Chrome (used by Selenium in headless mode)
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      # 5) Optional: show Chrome version for diagnostics
      - name: Check Chrome version
        run: chrome --version

      # 6) Run tests (continue-on-error ensures report is still generated)
      - name: Run tests
        run: mvn -B clean test
        continue-on-error: true

      # 7) Debug: list target and allure-results to confirm outputs exist
      - name: Debug list target
        if: always()
        run: |
          echo "--- target content ---"
          ls -la target || true
          echo "--- allure-results content ---"
          ls -la target/allure-results || true

      # 8) Load existing Allure history from gh-pages (for trends)
      - name: Load Allure history
        if: always()
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
        continue-on-error: true

      # 9) Generate Allure report (simple-elf action outputs to allure-history/)
      - name: Generate Allure report
        if: always()
        uses: simple-elf/allure-report-action@v1.13
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: target/allure-results

      # 9.5) Create root index.html that redirects to the latest report (handle permissions)
      - name: Point root index.html to latest report
        if: always()
        run: |
          # Find the latest numeric report folder (e.g., 31)
          latest=$(ls -1d allure-history/[0-9]* 2>/dev/null | sort -n | tail -1 | cut -d'/' -f2)
          if [ -z "$latest" ]; then latest="."; fi
          echo "Latest report folder: $latest"

          # Ensure we can write into allure-history (generated by a container as root)
          sudo chown -R $USER:$USER allure-history || true
          sudo chmod -R u+w allure-history || true

          # Write index.html using sudo-safe tee to avoid permission issues
          cat <<EOF | sudo tee allure-history/index.html > /dev/null
          <!-- Auto-redirect to latest Allure report -->
          <meta http-equiv="refresh" content="0; url=./$latest/index.html" />
          <script>location.href="./$latest/index.html";</script>
          EOF

          echo "Root index.html now points to: ${latest}/index.html"

      # 10) Deploy the report to gh-pages (skip on pull_request to avoid publishing)
      - name: Deploy report to gh-pages
        if: always() && github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
