name: Maven Tests with Allure Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}  # allows manual trigger from GitHub Actions UI

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout your project repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Cache Maven dependencies for faster builds
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Install Google Chrome for Selenium
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      # Optional: check installed Chrome version
      - name: Check Chrome version
        run: chrome --version

      # Run Maven tests (continue even if some tests fail)
      - name: Run tests
        run: mvn -B clean test
        continue-on-error: true

      # Debug: list contents of target folder to verify Allure results exist
      - name: Debug list target
        if: always()
        run: |
          echo "--- target content ---"
          ls -la target || true
          echo "--- allure-results content ---"
          ls -la target/allure-results || true

      # Retrieve previous Allure history (for trend data)
      - name: Load Allure history
        if: always()
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
        continue-on-error: true

      # Generate the Allure HTML report
      - name: Generate Allure report
        if: always()
        uses: simple-elf/allure-report-action@v1.13
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: target/allure-results

      # Deploy the report to GitHub Pages
      - name: Deploy report to gh-pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
